### ISSUE TITLE
Can't upload a zip

### ISSUE THREAD

**Issue by HolographicWings** [GreenTF/upload-thunderstore-package#28]
Hello, tried to use your Action to upload a Lethal Company mod
here my workflow
https://github.com/HolographicWings/LethalExpansion/blob/main/.github/workflows/release.yml
here the error
https://github.com/HolographicWings/LethalExpansion/actions/runs/7207501490/job/19634484153

did i failed anything ? i want to upload a premade zip instead of generating another one 

EDIT : 
i got this error too
https://github.com/HolographicWings/LethalSDK-Unity-Project/actions/runs/7207554043/job/19634627952 with my second package
the community and domains seems to be good (community is lethal-company and domain is default thunderstore.io)
the modpage is https://thunderstore.io/c/lethal-company

**Comment by Xenira** [comment]
I had the same as your second problem.
The solution was to add
```
repo: thunderstore.io
```

**Comment by HolographicWings** [comment]
> I had the same as your second problem. The solution was to add
> 
> ```
> repo: thunderstore.io
> ```

Thanks you that helped, i though it was the default repo choosen if no other one was provided
but that ain't fixed everything, i now have this issue : 
https://github.com/HolographicWings/LethalSDK-Unity-Project/actions/runs/7302794527/job/19902081909
workflow file : https://github.com/HolographicWings/LethalSDK-Unity-Project/actions/runs/7302794527/workflow

**Comment by Xenira** [comment]
The workflow creates a toml file that is used by the cli to build and upload as far as I understand it.
Not sure whats wrong though.

**Comment by HolographicWings** [comment]
Closed ? My issue is still not resolved

**Comment by HolographicWings** [comment]
@AnActualEmerald closed ? My issue is not resolved

**Comment by AnActualEmerald** [comment]
It still doesn't work with the new version?

**Comment by HolographicWings** [comment]
@AnActualEmerald closed ? My issue is not resolved

Oh my bad, I haven't saw the update, I will try today and tell you the result
So I keep the same workflow file ? You can confirm theres no error ?

**Comment by AnActualEmerald** [comment]
> So I keep the same workflow file
just change the version number for the action to 4.2, otherwise the rest should be okay. I can't say 100% it will solve your issue but I don't know what else it could be. I looked over your workflows and the errors you were getting and I'm not sure what was causing them, but I know lethal company mods weren't working previously because of an issue that was fixed in the update, so I want to see if that resolves it.

**Comment by HolographicWings** [comment]
> > So I keep the same workflow file
> 
> just change the version number for the action to 4.2, otherwise the rest should be okay. I can't say 100% it will solve your issue but I don't know what else it could be. I looked over your workflows and the errors you were getting and I'm not sure what was causing them, but I know lethal company mods weren't working previously because of an issue that was fixed in the update, so I want to see if that resolves it.

Hello, i still have a publish error
https://github.com/HolographicWings/LethalExpansion/actions/runs/7331776999/job/19964913800

**Comment by AnActualEmerald** [comment]
So I think I understand what's happening, I just don't know *why*. Judging by the error it looks like the changes to the `thunderstore.toml` either aren't being made at all or aren't being written. I'll see if I can reproduce this but unfortunately I don't have any solution in the meantime.

**Comment by AnActualEmerald** [comment]
OKAY I found the issue, sorry for not catching this earlier. The action should have reported an error but it didn't so I'll fix that. 

The issue is here:
```yaml
  deps: |
      BepInEx-BepInExPack-5.4.2100
```
dependencies need to be formatted like this:
```yaml
  deps: |
      BepInEx-BepInExPack@5.4.2100
```
that way it's easy to separate the version from the package name.

**Comment by HolographicWings** [comment]
Thanks you, i will try at the next occasion

**Comment by HolographicWings** [comment]
@AnActualEmerald It finally worked
thanks you for helping ^-^
https://github.com/HolographicWings/LethalExpansion/actions/runs/7359436381/job/20034206691
